// ccodegen.cpp — Luz → C source emitter.
//
// Emits a self-contained .c file that, when compiled with TCC or clang
// alongside luz_rt.c, produces a native binary.
//
// Design: emit_expr() returns a C expression string. Complex sub-expressions
// (dict literals, constructors) emit setup statements first, then return a
// variable name.  All Luz control-flow maps 1-to-1 to C — no SSA needed.

#include "luz/ccodegen.hpp"

#include <cassert>
#include <cstdio>
#include <ostream>
#include <sstream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace luz {
namespace {

// ── Helpers ───────────────────────────────────────────────────────────────────

std::string c_type(const std::string& hir_type) {
    if (hir_type == "int"    || hir_type == "int?"   ) return "long long";
    if (hir_type == "float"  || hir_type == "float?" ) return "double";
    if (hir_type == "bool"   || hir_type == "bool?"  ) return "int";
    if (hir_type == "string" || hir_type == "string?") return "char*";
    if (hir_type == "dict"   || hir_type == "list"   ) return "LuzDict*";
    if (hir_type == "void"                           ) return "void";
    if (hir_type.empty() || hir_type == "unknown"   ) return "long long";
    return "LuzDict*";  // user-defined class
}

std::string c_ret_type(const std::string& hir_type) {
    if (hir_type.empty() || hir_type == "unknown") return "void";
    return c_type(hir_type);
}

std::string escape_c(const std::string& s) {
    std::string out;
    for (unsigned char c : s) {
        if      (c == '"' ) out += "\\\"";
        else if (c == '\\') out += "\\\\";
        else if (c == '\n') out += "\\n";
        else if (c == '\r') out += "\\r";
        else if (c == '\t') out += "\\t";
        else if (c < 32 || c > 126) {
            char buf[8]; std::snprintf(buf, sizeof(buf), "\\x%02x", c);
            out += buf;
        } else {
            out += static_cast<char>(c);
        }
    }
    return out;
}

// ── CCodeGen ─────────────────────────────────────────────────────────────────

class CCodeGen {
public:
    explicit CCodeGen(std::ostream& out) : out_(out) {}

    void emit_module(const HirBlock& program, const std::string& filename) {
        collect_classes(program);

        out_ << "/* generated by luzc from " << filename << " */\n"
             << "#include <stdio.h>\n#include <stdlib.h>\n"
             << "#include <string.h>\n#include <setjmp.h>\n\n";

        emit_rt_decls();
        emit_forward_decls(program);

        std::vector<HirNode*> classes, funcs, stmts;
        for (auto& n : program) {
            if      (n->kind == HirKind::ClassDef)  classes.push_back(n.get());
            else if (n->kind == HirKind::FuncDef)   funcs.push_back(n.get());
            else if (n->kind == HirKind::StructDef ||
                     n->kind == HirKind::Import)    { /* handled separately */ }
            else                                    stmts.push_back(n.get());
        }

        // Pre-pass: collect and emit nested FuncDef nodes as top-level functions
        // so they are available before main() and class methods that reference them.
        {
            std::vector<HirFuncDef*> nested;
            for (auto* f : funcs) {
                collect_nested_funcs(static_cast<HirFuncDef*>(f)->body, nested);
            }
            for (auto* fn : nested) {
                if (!nested_emitted_.count(fn->name)) {
                    // Emit forward decl
                    std::string frt = c_ret_type(fn->return_type);
                    if (frt == "void" && (fn->return_type.empty() || fn->return_type == "unknown"))
                        frt = scan_return_type(fn->body);
                    out_ << frt << " " << fn->name << "(";
                    if (fn->params.empty()) out_ << "void";
                    for (int i = 0; i < (int)fn->params.size(); ++i) {
                        if (i) out_ << ", ";
                        out_ << c_type(fn->params[i].type) << " " << fn->params[i].name;
                    }
                    out_ << ");\n";
                    nested_emitted_.insert(fn->name);
                    lambdas_.insert(fn->name);
                }
            }
            for (auto* fn : nested) {
                emit_func(fn, "", false);
            }
        }

        for (auto* c : classes) emit_class(static_cast<HirClassDef*>(c));
        for (auto* f : funcs)   emit_func(static_cast<HirFuncDef*>(f), "", false);

        out_ << "\nint main(void) {\n";
        indent_ = 1;
        for (auto* s : stmts) emit_stmt(s);
        line("return 0;");
        indent_ = 0;
        out_ << "}\n";
    }

private:
    std::ostream& out_;
    int    indent_       = 0;
    int    tmp_id_       = 0;
    std::string current_ret_;
    std::string current_class_;

    std::unordered_map<std::string, std::string> locals_;   // name → C type
    std::unordered_set<std::string>              lambdas_;  // lambda var names

    struct ClassInfo {
        std::string parent;
        std::vector<std::string> methods;
        std::unordered_map<std::string, std::string> field_types;
        std::unordered_map<std::string, std::string> method_ret;
    };
    std::unordered_map<std::string, ClassInfo> classes_;

    // ── Utilities ─────────────────────────────────────────────────────────────

    void line(const std::string& s) {
        for (int i = 0; i < indent_; ++i) out_ << "    ";
        out_ << s << "\n";
    }

    std::string tmp() { return "__t" + std::to_string(tmp_id_++); }

    static std::string dict_setter(const std::string& ct) {
        if (ct == "long long") return "luz_dict_set_int";
        if (ct == "double")    return "luz_dict_set_float";
        if (ct == "int")       return "luz_dict_set_bool";
        return "luz_dict_set_str";
    }
    static std::string dict_getter(const std::string& ct) {
        if (ct == "long long") return "luz_dict_get_int";
        if (ct == "double")    return "luz_dict_get_float";
        if (ct == "int")       return "luz_dict_get_bool";
        return "luz_dict_get_str";
    }

    // ── Runtime declarations (inlined in the generated file) ─────────────────

    void emit_rt_decls() {
        out_ <<
            "typedef struct LuzDict LuzDict;\n"
            "extern LuzDict* luz_dict_new(void);\n"
            "extern void     luz_dict_set_int(LuzDict*,const char*,long long);\n"
            "extern void     luz_dict_set_float(LuzDict*,const char*,double);\n"
            "extern void     luz_dict_set_bool(LuzDict*,const char*,int);\n"
            "extern void     luz_dict_set_str(LuzDict*,const char*,const char*);\n"
            "extern long long luz_dict_get_int(LuzDict*,const char*);\n"
            "extern double    luz_dict_get_float(LuzDict*,const char*);\n"
            "extern int       luz_dict_get_bool(LuzDict*,const char*);\n"
            "extern char*     luz_dict_get_str(LuzDict*,const char*);\n"
            "extern long long luz_dict_len(LuzDict*);\n"
            "extern int       luz_dict_contains(LuzDict*,const char*);\n"
            "extern void      luz_dict_remove(LuzDict*,const char*);\n"
            "extern char*     luz_str_concat(const char*,const char*);\n"
            "extern char*     luz_to_str_int(long long);\n"
            "extern char*     luz_to_str_float(double);\n"
            "extern char*     luz_to_str_bool(int);\n"
            "extern long long luz_str_len(const char*);\n"
            "extern int       luz_str_eq(const char*,const char*);\n"
            "extern int       luz_str_contains(const char*,const char*);\n"
            "extern void      luz_push_rescue_ptr(void*);\n"
            "extern void      luz_pop_rescue(void);\n"
            "extern void      luz_alert_throw(const char*);\n"
            "extern const char* luz_get_error(void);\n"
            "extern long long luz_powi(long long,long long);\n"
            "extern char*     luz_listen(const char*);\n"
            "extern long long luz_to_int(const char*);\n"
            "extern double    luz_to_float(const char*);\n"
            "extern int       luz_to_bool(const char*);\n"
            "extern char*     luz_idx_key(long long);\n"
            "extern void      luz_list_append(LuzDict*,long long);\n"
            "extern long long luz_list_pop(LuzDict*);\n"
            "extern void      luz_list_sort(LuzDict*);\n\n";
    }

    // ── Class registry ────────────────────────────────────────────────────────

    void collect_classes(const HirBlock& program) {
        // Structs first
        for (auto& n : program) {
            if (n->kind != HirKind::StructDef) continue;
            auto* s = static_cast<HirStructDef*>(n.get());
            ClassInfo info;
            for (auto& f : s->fields) info.field_types[f.name] = c_type(f.type);
            classes_[s->name] = std::move(info);
        }
        // Classes
        for (auto& n : program) {
            if (n->kind != HirKind::ClassDef) continue;
            auto* cls = static_cast<HirClassDef*>(n.get());
            ClassInfo info;
            info.parent = cls->parent;
            for (auto& m : cls->methods) {
                if (m->kind != HirKind::FuncDef) continue;
                auto* fn = static_cast<HirFuncDef*>(m.get());
                info.methods.push_back(fn->name);
                std::string rt = c_ret_type(fn->return_type);
                if (rt == "void" && (fn->return_type.empty() || fn->return_type == "unknown"))
                    rt = scan_return_type(fn->body);
                info.method_ret[fn->name] = rt;
                if (fn->name == "init") {
                    std::unordered_map<std::string, std::string> pt;
                    for (auto& p : fn->params) pt[p.name] = c_type(p.type);
                    for (auto& nd : fn->body) {
                        if (nd->kind != HirKind::FieldStore) continue;
                        auto* fs = static_cast<HirFieldStore*>(nd.get());
                        if (info.field_types.count(fs->field)) continue;
                        if (fs->value->kind == HirKind::Load) {
                            auto it = pt.find(static_cast<HirLoad*>(fs->value.get())->name);
                            if (it != pt.end()) info.field_types[fs->field] = it->second;
                        } else if (fs->value->kind == HirKind::Literal) {
                            auto* lit = static_cast<HirLiteral*>(fs->value.get());
                            switch (lit->vk) {
                            case HirLiteral::ValKind::Int:    info.field_types[fs->field] = "long long"; break;
                            case HirLiteral::ValKind::Float:  info.field_types[fs->field] = "double"; break;
                            case HirLiteral::ValKind::Bool:   info.field_types[fs->field] = "int"; break;
                            default:                          info.field_types[fs->field] = "char*"; break;
                            }
                        }
                    }
                }
            }
            classes_[cls->name] = std::move(info);
        }
    }

    std::string resolve_method_owner(const std::string& cls, const std::string& method) {
        std::string cur = cls;
        while (!cur.empty()) {
            auto it = classes_.find(cur);
            if (it == classes_.end()) break;
            for (auto& m : it->second.methods) if (m == method) return cur;
            cur = it->second.parent;
        }
        return cls;
    }

    std::string resolve_field_type(const std::string& cls, const std::string& field) {
        std::string cur = cls;
        while (!cur.empty()) {
            auto it = classes_.find(cur);
            if (it == classes_.end()) break;
            auto fit = it->second.field_types.find(field);
            if (fit != it->second.field_types.end()) return fit->second;
            cur = it->second.parent;
        }
        return "char*";
    }

    // ── Forward declarations ──────────────────────────────────────────────────

    void emit_forward_decls(const HirBlock& program) {
        bool any = false;
        for (auto& n : program) {
            if (n->kind == HirKind::FuncDef) {
                auto* fn = static_cast<HirFuncDef*>(n.get());
                if (!any) { out_ << "/* forward declarations */\n"; any = true; }
                std::string frt = c_ret_type(fn->return_type);
                if (frt == "void" && (fn->return_type.empty() || fn->return_type == "unknown"))
                    frt = scan_return_type(fn->body);
                out_ << frt << " " << fn->name << "(";
                if (fn->params.empty()) out_ << "void";
                for (int i = 0; i < (int)fn->params.size(); ++i) {
                    if (i) out_ << ", ";
                    out_ << c_type(fn->params[i].type) << " " << fn->params[i].name;
                }
                out_ << ");\n";
            } else if (n->kind == HirKind::ClassDef) {
                auto* cls = static_cast<HirClassDef*>(n.get());
                for (auto& m : cls->methods) {
                    if (m->kind != HirKind::FuncDef) continue;
                    auto* fn = static_cast<HirFuncDef*>(m.get());
                    if (!any) { out_ << "/* forward declarations */\n"; any = true; }
                    std::string rt = c_ret_type(fn->return_type);
                    if (rt == "void" && (fn->return_type.empty() || fn->return_type == "unknown"))
                        rt = scan_return_type(fn->body);
                    out_ << rt << " " << cls->name << "__" << fn->name << "(LuzDict* self";
                    for (auto& p : fn->params) out_ << ", " << c_type(p.type) << " " << p.name;
                    out_ << ");\n";
                }
            }
        }
        if (any) out_ << "\n";
    }

    // Scan a block for return-with-value to infer a return type.
    std::string scan_return_type(const HirBlock& body) {
        for (auto& n : body) {
            if (n->kind == HirKind::Return) {
                auto* r = static_cast<HirReturn*>(n.get());
                if (r->value) {
                    // Recurse into the value's type tag
                    if (r->value->kind == HirKind::Literal) {
                        auto* l = static_cast<HirLiteral*>(r->value.get());
                        switch (l->vk) {
                        case HirLiteral::ValKind::Int:    return "long long";
                        case HirLiteral::ValKind::Float:  return "double";
                        case HirLiteral::ValKind::Bool:   return "int";
                        default:                          return "char*";
                        }
                    }
                    if (r->value->kind == HirKind::Load) {
                        auto* l = static_cast<HirLoad*>(r->value.get());
                        return c_type(l->type);  // may be long long for unknown
                    }
                    // BinOp used to hardcode "long long", which truncated
                    // float-returning expressions like `(a + b) / 2.0` to
                    // an int return type and broke any function that
                    // returned a non-int arithmetic result (issue #99).
                    // Defer to infer_type so the HIR's type tag drives the
                    // forward-declared return type.
                    if (r->value->kind == HirKind::BinOp)
                        return infer_type(r->value.get());
                    if (r->value->kind == HirKind::Call) {
                        auto* c = static_cast<HirCall*>(r->value.get());
                        return c_ret_type(c->return_type);
                    }
                    return "long long";
                }
            }
            // Recurse into if/while
            if (n->kind == HirKind::If) {
                auto* i = static_cast<HirIf*>(n.get());
                std::string t = scan_return_type(i->then_block);
                if (!t.empty() && t != "void") return t;
                t = scan_return_type(i->else_block);
                if (!t.empty() && t != "void") return t;
            }
            if (n->kind == HirKind::While) {
                auto* w = static_cast<HirWhile*>(n.get());
                std::string t = scan_return_type(w->body);
                if (!t.empty() && t != "void") return t;
            }
        }
        return "void";
    }

    // ── Type inference from HIR node ──────────────────────────────────────────

    std::string infer_type(HirNode* n) {
        if (!n) return "long long";
        switch (n->kind) {
        case HirKind::Literal: {
            auto* l = static_cast<HirLiteral*>(n);
            switch (l->vk) {
            case HirLiteral::ValKind::Int:    return "long long";
            case HirLiteral::ValKind::Float:  return "double";
            case HirLiteral::ValKind::Bool:   return "int";
            case HirLiteral::ValKind::String: return "char*";
            default: return "long long";
            }
        }
        case HirKind::Load: {
            auto* l = static_cast<HirLoad*>(n);
            auto it = locals_.find(l->name);
            if (it != locals_.end()) return it->second;
            return c_type(l->type);
        }
        case HirKind::BinOp: {
            auto* b = static_cast<HirBinOp*>(n);
            const std::string& op = b->op;
            if (op=="=="||op=="!="||op=="<"||op=="<="||op==">"||op==">="||op=="and"||op=="or")
                return "int";
            if (op == "+" && (infer_type(b->left.get()) == "char*" ||
                               infer_type(b->right.get()) == "char*"))
                return "char*";
            return c_type(b->type);
        }
        case HirKind::Call: {
            auto* c = static_cast<HirCall*>(n);
            if (classes_.count(c->func)) return "LuzDict*";
            if (c->func == "range") return "LuzDict*";
            if (c->func == "type" || c->func == "typeof") return "char*";
            std::string rt = c->return_type;
            if (rt.empty() || rt == "unknown") {
                auto fit = func_ret_.find(c->func);
                if (fit != func_ret_.end()) return fit->second;
                return "long long";
            }
            return c_type(rt);
        }
        case HirKind::FieldLoad: {
            auto* fl = static_cast<HirFieldLoad*>(n);
            std::string ft = c_type(fl->type);
            if ((ft == "long long" || ft == "void") &&
                (fl->type.empty() || fl->type == "unknown")) {
                std::string cls = load_class_name(fl->obj.get());
                ft = resolve_field_type(cls, fl->field);
            }
            if (ft == "void") ft = "char*";
            return ft;
        }
        case HirKind::Dict: return "LuzDict*";
        case HirKind::List: return "LuzDict*";
        case HirKind::ObjectCall: {
            auto* oc = static_cast<HirObjectCall*>(n);
            if (!oc->return_type.empty() && oc->return_type != "unknown")
                return c_type(oc->return_type);
            std::string cls = load_class_name(oc->obj.get());
            std::string owner = resolve_method_owner(cls, oc->method);
            auto cit = classes_.find(owner);
            if (cit != classes_.end()) {
                auto rit = cit->second.method_ret.find(oc->method);
                if (rit != cit->second.method_ret.end()) return rit->second;
            }
            return "long long";
        }
        default: return "long long";
        }
    }

    std::string luz_hir_type(HirNode* n) {
        if (n->kind == HirKind::Load) {
            auto* l = static_cast<HirLoad*>(n);
            if (!l->type.empty() && l->type != "unknown") return l->type;
            auto it = locals_.find(l->name);
            if (it != locals_.end()) {
                if (it->second == "LuzDict*") {
                    // Try to recover class name from a separate map — use load type
                    return l->type;
                }
                return it->second == "char*" ? "string" : l->type;
            }
        }
        if (n->kind == HirKind::Dict) return "dict";
        return "";
    }

    std::string to_cstr(const std::string& val, const std::string& ct) {
        if (ct == "long long") return "luz_to_str_int(" + val + ")";
        if (ct == "double")    return "luz_to_str_float(" + val + ")";
        if (ct == "int")       return "luz_to_str_bool(" + val + ")";
        return val;
    }

    // ── Expression emission ───────────────────────────────────────────────────

    // Returns a C expression (may emit setup statements first for complex exprs)
    std::string expr(HirNode* n) {
        switch (n->kind) {
        case HirKind::Literal:    return emit_literal(static_cast<HirLiteral*>(n));
        case HirKind::Load:       return static_cast<HirLoad*>(n)->name;
        case HirKind::BinOp:      return emit_binop(static_cast<HirBinOp*>(n));
        case HirKind::UnaryOp:    return emit_unary(static_cast<HirUnaryOp*>(n));
        case HirKind::Call:       return emit_call_expr(static_cast<HirCall*>(n));
        case HirKind::FieldLoad:  return emit_field_load(static_cast<HirFieldLoad*>(n));
        case HirKind::ObjectCall: return emit_objcall_expr(static_cast<HirObjectCall*>(n));
        case HirKind::Dict:       return emit_dict_expr(static_cast<HirDict*>(n));
        case HirKind::List:       return emit_list_expr(static_cast<HirList*>(n));
        case HirKind::Index:      return emit_index_expr(static_cast<HirIndex*>(n));
        case HirKind::If: {
            // if-as-expression: emit as temp variable
            auto* i = static_cast<HirIf*>(n);
            std::string tv = tmp();
            line("long long " + tv + " = 0;");
            emit_if_to_var(tv, i);
            return tv;
        }
        case HirKind::ExprCall: return "0";
        default: return "0";
        }
    }

    void emit_if_to_var(const std::string& var, HirIf* n) {
        line("if (" + expr(n->cond.get()) + ") {");
        indent_++;
        emit_block(n->then_block);
        indent_--;
        if (!n->else_block.empty()) {
            line("} else {");
            indent_++;
            emit_block(n->else_block);
            indent_--;
        }
        line("}");
        (void)var;
    }

    std::string emit_literal(HirLiteral* n) {
        switch (n->vk) {
        case HirLiteral::ValKind::Int:    return std::to_string(n->i) + "LL";
        case HirLiteral::ValKind::Float: {
            std::ostringstream ss; ss << n->f;
            std::string s = ss.str();
            if (s.find('.') == std::string::npos && s.find('e') == std::string::npos) s += ".0";
            return s;
        }
        case HirLiteral::ValKind::Bool:   return n->b ? "1" : "0";
        case HirLiteral::ValKind::String: return "\"" + escape_c(n->s) + "\"";
        case HirLiteral::ValKind::Null:   return "0";
        }
        return "0";
    }

    std::string emit_binop(HirBinOp* n) {
        std::string lv = expr(n->left.get());
        std::string rv = expr(n->right.get());
        std::string lt = infer_type(n->left.get());
        std::string rt = infer_type(n->right.get());
        bool is_str = (lt == "char*" || rt == "char*");

        if (n->op == "+" && is_str) {
            std::string la = lt != "char*" ? to_cstr(lv, lt) : lv;
            std::string ra = rt != "char*" ? to_cstr(rv, rt) : rv;
            return "luz_str_concat(" + la + ", " + ra + ")";
        }
        if ((n->op == "==" || n->op == "!=") && is_str) {
            std::string eq = "luz_str_eq(" + lv + ", " + rv + ")";
            return n->op == "!=" ? "(!" + eq + ")" : eq;
        }
        if (n->op == "and") return "(" + lv + " && " + rv + ")";
        if (n->op == "or")  return "(" + lv + " || " + rv + ")";
        if (n->op == "**")  return "luz_powi(" + lv + ", " + rv + ")";
        if (n->op == "//")  return "(" + lv + " / " + rv + ")";
        return "(" + lv + " " + n->op + " " + rv + ")";
    }

    std::string emit_unary(HirUnaryOp* n) {
        std::string v = expr(n->operand.get());
        if (n->op == "not") return "(!" + v + ")";
        return "(-" + v + ")";
    }

    std::string emit_call_expr(HirCall* n) {
        // write / print
        if (n->func == "write" || n->func == "print") {
            if (!n->args.empty()) {
                std::string v = expr(n->args[0].get());
                std::string t = infer_type(n->args[0].get());
                if (t == "long long")   line("printf(\"%lld\\n\", " + v + ");");
                else if (t == "double") line("printf(\"%g\\n\", " + v + ");");
                else if (t == "char*")  line("printf(\"%s\\n\", " + v + ");");
                else /* bool/int */     line("printf(\"%s\\n\", (" + v + ") ? \"true\" : \"false\");");
            }
            return "";
        }
        if (n->func == "to_str") {
            if (n->args.empty()) return "\"\"";
            std::string v = expr(n->args[0].get());
            return to_cstr(v, infer_type(n->args[0].get()));
        }
        if (n->func == "len" && !n->args.empty()) {
            std::string v = expr(n->args[0].get());
            std::string ht = luz_hir_type(n->args[0].get());
            if (ht == "dict" || ht == "list" || infer_type(n->args[0].get()) == "LuzDict*")
                return "luz_dict_len((LuzDict*)" + v + ")";
            return "luz_str_len(" + v + ")";
        }
        if (n->func == "contains" && n->args.size() >= 2) {
            std::string obj = expr(n->args[0].get());
            std::string nd  = expr(n->args[1].get());
            std::string ht  = luz_hir_type(n->args[0].get());
            if (ht == "dict" || infer_type(n->args[0].get()) == "LuzDict*")
                return "luz_dict_contains((LuzDict*)" + obj + ", " + nd + ")";
            return "luz_str_contains(" + obj + ", " + nd + ")";
        }
        if (n->func == "remove" && n->args.size() >= 2) {
            line("luz_dict_remove((LuzDict*)" + expr(n->args[0].get()) + ", " + expr(n->args[1].get()) + ");");
            return "";
        }
        if (n->func == "exit") {
            line("exit((int)" + (n->args.empty() ? std::string("0") : expr(n->args[0].get())) + ");");
            return "";
        }
        if (n->func == "listen") {
            std::string prompt = n->args.empty() ? "\"\"" : expr(n->args[0].get());
            return "luz_listen(" + prompt + ")";
        }
        if (n->func == "to_int") {
            std::string v = n->args.empty() ? "\"\"" : expr(n->args[0].get());
            return "luz_to_int(" + v + ")";
        }
        if (n->func == "to_float") {
            std::string v = n->args.empty() ? "\"\"" : expr(n->args[0].get());
            return "luz_to_float(" + v + ")";
        }
        if (n->func == "to_bool") {
            std::string v = n->args.empty() ? "\"\"" : expr(n->args[0].get());
            return "luz_to_bool(" + v + ")";
        }
        // sort(list)
        if (n->func == "sort" && !n->args.empty()) {
            line("luz_list_sort((LuzDict*)" + expr(n->args[0].get()) + ");");
            return "";
        }
        // type(x) / typeof(x)
        if ((n->func == "type" || n->func == "typeof") && !n->args.empty()) {
            std::string t = infer_type(n->args[0].get());
            std::string type_name;
            if      (t == "long long") type_name = "\"int\"";
            else if (t == "double")    type_name = "\"float\"";
            else if (t == "int")       type_name = "\"bool\"";
            else if (t == "char*")     type_name = "\"string\"";
            else                       type_name = "\"object\"";
            std::string v = expr(n->args[0].get());
            (void)v;
            return type_name;
        }
        // range()
        if (n->func == "range") {
            std::string obj = tmp();
            line("LuzDict* " + obj + " = luz_dict_new();");
            if (n->args.size() == 1) {
                std::string count = expr(n->args[0].get());
                std::string i = tmp();
                line("long long " + i + " = 0;");
                line("while (" + i + " < " + count + ") {");
                indent_++;
                line("luz_dict_set_int(" + obj + ", luz_idx_key(" + i + "), " + i + ");");
                line(i + "++;");
                indent_--;
                line("}");
            } else if (n->args.size() >= 2) {
                std::string start = expr(n->args[0].get());
                std::string end   = expr(n->args[1].get());
                std::string step  = n->args.size() >= 3 ? expr(n->args[2].get()) : "1LL";
                std::string i  = tmp();
                std::string ki = tmp();
                line("long long " + i + " = " + start + ";");
                line("long long " + ki + " = 0;");
                line("while (" + i + " < " + end + ") {");
                indent_++;
                line("luz_dict_set_int(" + obj + ", luz_idx_key(" + ki + "), " + i + ");");
                line(i + " += " + step + ";");
                line(ki + "++;");
                indent_--;
                line("}");
            }
            return obj;
        }
        // append / pop
        if (n->func == "append" && n->args.size() >= 2) {
            std::string list = expr(n->args[0].get());
            std::string val  = expr(n->args[1].get());
            line("luz_list_append((LuzDict*)" + list + ", " + val + ");");
            return "";
        }
        if (n->func == "pop" && !n->args.empty()) {
            std::string list = expr(n->args[0].get());
            return "luz_list_pop((LuzDict*)" + list + ")";
        }
        // Constructor
        if (classes_.count(n->func)) {
            std::string obj = tmp();
            line("LuzDict* " + obj + " = luz_dict_new();");
            std::string owner = resolve_method_owner(n->func, "init");
            auto cit = classes_.find(owner);
            bool has_init = cit != classes_.end() &&
                [&]{ for(auto& m: cit->second.methods) if(m=="init") return true; return false; }();
            if (has_init) {
                std::string args = obj;
                for (auto& a : n->args) args += ", " + expr(a.get());
                line(owner + "__init(" + args + ");");
            }
            return obj;
        }
        // Lambda
        if (lambdas_.count(n->func)) {
            std::string args;
            for (int i = 0; i < (int)n->args.size(); ++i) {
                if (i) args += ", ";
                args += expr(n->args[i].get());
            }
            return n->func + "(" + args + ")";
        }
        // Regular function
        std::string rt = c_ret_type(n->return_type);
        std::string args;
        for (int i = 0; i < (int)n->args.size(); ++i) {
            if (i) args += ", ";
            args += expr(n->args[i].get());
        }
        std::string call = n->func + "(" + args + ")";
        // Only treat as a void statement when the return type is explicitly void,
        // not when it's unknown (unknown functions may still return a value).
        if (rt == "void" && n->return_type == "void") { line(call + ";"); return ""; }
        return call;
    }

    std::string emit_field_load(HirFieldLoad* n) {
        std::string obj = expr(n->obj.get());
        std::string ft  = c_type(n->type);
        if ((ft == "long long" || ft == "void") &&
            (n->type.empty() || n->type == "unknown")) {
            // Look up from class registry
            std::string cls = load_class_name(n->obj.get());
            ft = resolve_field_type(cls, n->field);
        }
        if (ft == "void") ft = "char*";
        return dict_getter(ft) + "((LuzDict*)" + obj + ", \"" + n->field + "\")";
    }

    std::string emit_objcall_expr(HirObjectCall* n) {
        std::string obj   = expr(n->obj.get());
        std::string cls   = load_class_name(n->obj.get());
        std::string owner = resolve_method_owner(cls, n->method);
        std::string rt    = n->return_type.empty() || n->return_type == "unknown"
                            ? "void" : c_ret_type(n->return_type);
        if (rt == "void") {
            auto cit = classes_.find(owner);
            if (cit != classes_.end()) {
                auto rit = cit->second.method_ret.find(n->method);
                if (rit != cit->second.method_ret.end()) rt = rit->second;
            }
        }
        std::string args = obj;
        for (auto& a : n->args) args += ", " + expr(a.get());
        std::string call = owner + "__" + n->method + "(" + args + ")";
        if (rt == "void") { line(call + ";"); return ""; }
        return call;
    }

    std::string emit_dict_expr(HirDict* n) {
        std::string v = tmp();
        line("LuzDict* " + v + " = luz_dict_new();");
        for (auto& p : n->pairs) {
            std::string k  = expr(p.key.get());
            std::string vv = expr(p.value.get());
            std::string vt = infer_type(p.value.get());
            line(dict_setter(vt) + "(" + v + ", " + k + ", " + vv + ");");
        }
        return v;
    }

    std::string emit_list_expr(HirList* n) {
        std::string v = tmp();
        line("LuzDict* " + v + " = luz_dict_new();");
        for (int i = 0; i < (int)n->elements.size(); ++i) {
            std::string elem = expr(n->elements[i].get());
            std::string et   = infer_type(n->elements[i].get());
            std::string key  = "\"" + std::to_string(i) + "\"";
            line(dict_setter(et) + "(" + v + ", " + key + ", " + elem + ");");
        }
        return v;
    }

    std::string emit_index_expr(HirIndex* n) {
        std::string coll = expr(n->collection.get());
        std::string idx  = expr(n->index.get());
        std::string rt   = c_type(n->type);
        if (rt == "void") rt = "char*";
        // Integer indices must be converted to string keys for the dict runtime
        std::string key = infer_type(n->index.get()) == "long long"
                          ? "luz_idx_key(" + idx + ")"
                          : idx;
        return dict_getter(rt) + "((LuzDict*)" + coll + ", " + key + ")";
    }

    // Get the class name for self / object variables
    std::string load_class_name(HirNode* n) {
        if (n->kind == HirKind::Load) {
            auto* l = static_cast<HirLoad*>(n);
            if (l->name == "self") return current_class_;
            if (!l->type.empty() && l->type != "unknown") return l->type;
            // Check locals for hir_type tracking
            auto it = class_of_var_.find(l->name);
            if (it != class_of_var_.end()) return it->second;
        }
        return "";
    }

    std::unordered_map<std::string, std::string> class_of_var_; // var → class name
    std::unordered_map<std::string, std::string> func_ret_;    // func name → C return type
    std::unordered_set<std::string>              nested_emitted_; // nested func names already emitted

    // ── Statements ────────────────────────────────────────────────────────────

    void emit_stmt(HirNode* n) {
        switch (n->kind) {
        case HirKind::Let:           emit_let(static_cast<HirLet*>(n));               break;
        case HirKind::Assign:        emit_assign(static_cast<HirAssign*>(n));         break;
        case HirKind::If:            emit_if(static_cast<HirIf*>(n));                 break;
        case HirKind::While:         emit_while(static_cast<HirWhile*>(n));           break;
        case HirKind::Return:        emit_return(static_cast<HirReturn*>(n));         break;
        case HirKind::Break:         line("break;");                                  break;
        case HirKind::Continue:      line("continue;");                               break;
        case HirKind::Pass:                                                            break;
        case HirKind::Alert:         emit_alert(static_cast<HirAlert*>(n));           break;
        case HirKind::AttemptRescue: emit_attempt(static_cast<HirAttemptRescue*>(n));break;
        case HirKind::FieldStore:    emit_field_store(static_cast<HirFieldStore*>(n));break;
        case HirKind::IndexStore:    emit_index_store(static_cast<HirIndexStore*>(n));break;
        case HirKind::FuncDef:       emit_lambda_local(static_cast<HirFuncDef*>(n)); break;
        case HirKind::ObjectCall:
        case HirKind::Call: {
            std::string e = expr(n);
            if (!e.empty()) line(e + ";");
            break;
        }
        case HirKind::ClassDef:
        case HirKind::StructDef:
        case HirKind::Import:        break;
        default: {
            std::string e = expr(n);
            if (!e.empty()) line(e + ";");
            break;
        }
        }
    }

    void emit_block(const HirBlock& blk) {
        for (auto& n : blk) emit_stmt(n.get());
    }

    void emit_let(HirLet* n) {
        if (n->value && n->value->kind == HirKind::FuncDef) {
            emit_lambda_def(n->name, static_cast<HirFuncDef*>(n->value.get()));
            return;
        }
        std::string ct = c_type(n->type);
        if (ct == "void") ct = "long long";
        if (ct == "long long" && classes_.count(n->type)) ct = "LuzDict*";
        std::string v = expr(n->value.get());
        line(ct + " " + n->name + " = " + v + ";");
        locals_[n->name] = ct;
        if (ct == "LuzDict*") class_of_var_[n->name] = n->type;
    }

    void emit_assign(HirAssign* n) {
        if (n->value && n->value->kind == HirKind::FuncDef) {
            emit_lambda_def(n->name, static_cast<HirFuncDef*>(n->value.get()));
            return;
        }
        std::string v = expr(n->value.get());
        auto it = locals_.find(n->name);
        if (it == locals_.end()) {
            std::string ct = infer_type(n->value.get());
            if (ct == "void" || ct.empty()) ct = "long long";
            line(ct + " " + n->name + " = " + v + ";");
            locals_[n->name] = ct;
            if (ct == "LuzDict*") {
                // Track which class this variable holds
                if (n->value->kind == HirKind::Call) {
                    auto* call = static_cast<HirCall*>(n->value.get());
                    if (classes_.count(call->func))
                        class_of_var_[n->name] = call->func;
                } else {
                    std::string ht = luz_hir_type(n->value.get());
                    if (!ht.empty()) class_of_var_[n->name] = ht;
                }
            }
        } else {
            line(n->name + " = " + v + ";");
        }
    }

    void emit_if(HirIf* n) {
        line("if (" + expr(n->cond.get()) + ") {");
        indent_++;
        emit_block(n->then_block);
        indent_--;
        if (!n->else_block.empty()) {
            line("} else {");
            indent_++;
            emit_block(n->else_block);
            indent_--;
        }
        line("}");
    }

    void emit_while(HirWhile* n) {
        line("while (" + expr(n->cond.get()) + ") {");
        indent_++;
        emit_block(n->body);
        indent_--;
        line("}");
    }

    void emit_return(HirReturn* n) {
        if (!n->value || current_ret_ == "void")
            line("return;");
        else
            line("return " + expr(n->value.get()) + ";");
    }

    void emit_alert(HirAlert* n) {
        std::string v = expr(n->value.get());
        std::string t = infer_type(n->value.get());
        line("luz_alert_throw(" + (t == "char*" ? v : to_cstr(v, t)) + ");");
    }

    void emit_attempt(HirAttemptRescue* n) {
        line("{");
        indent_++;
        line("jmp_buf __rescue_buf;");
        line("luz_push_rescue_ptr(&__rescue_buf);");
        line("if (setjmp(__rescue_buf) == 0) {");
        indent_++;
        emit_block(n->try_block);
        line("luz_pop_rescue();");
        indent_--;
        line("} else {");
        indent_++;
        if (!n->error_var.empty()) {
            line("const char* " + n->error_var + " = luz_get_error();");
            locals_[n->error_var] = "char*";
        }
        emit_block(n->rescue_block);
        indent_--;
        line("}");
        emit_block(n->finally_block);
        indent_--;
        line("}");
    }

    void emit_field_store(HirFieldStore* n) {
        std::string obj = expr(n->obj.get());
        std::string v   = expr(n->value.get());
        std::string vt  = infer_type(n->value.get());
        line(dict_setter(vt) + "((LuzDict*)" + obj + ", \"" + n->field + "\", " + v + ");");
    }

    void emit_index_store(HirIndexStore* n) {
        std::string coll = expr(n->collection.get());
        std::string idx  = expr(n->index.get());
        std::string v    = expr(n->value.get());
        std::string vt   = infer_type(n->value.get());
        // Integer indices must be converted to string keys for the dict runtime
        std::string key = infer_type(n->index.get()) == "long long"
                          ? "luz_idx_key(" + idx + ")"
                          : idx;
        line(dict_setter(vt) + "((LuzDict*)" + coll + ", " + key + ", " + v + ");");
    }

    // ── Functions ─────────────────────────────────────────────────────────────

    void emit_func(HirFuncDef* n, const std::string& class_prefix, bool is_method) {
        auto saved_locals = locals_;
        auto saved_ret    = current_ret_;
        auto saved_cls    = current_class_;
        auto saved_cov    = class_of_var_;
        int  saved_tmp    = tmp_id_;

        std::string rt = c_ret_type(n->return_type);
        if (rt == "void" && (n->return_type.empty() || n->return_type == "unknown"))
            rt = scan_return_type(n->body);
        current_ret_   = rt;
        if (is_method && !class_prefix.empty()) current_class_ = class_prefix;

        std::string full_name = class_prefix.empty() ? n->name : class_prefix + "__" + n->name;
        func_ret_[full_name] = rt;

        out_ << "\n" << rt << " " << full_name << "(";
        if (is_method) {
            out_ << "LuzDict* self";
            locals_["self"] = "LuzDict*";
            if (!n->params.empty()) out_ << ", ";
        } else if (n->params.empty()) {
            out_ << "void";
        }
        for (int i = 0; i < (int)n->params.size(); ++i) {
            if (i) out_ << ", ";
            std::string ct = c_type(n->params[i].type);
            out_ << ct << " " << n->params[i].name;
            locals_[n->params[i].name] = ct;
        }
        out_ << ") {\n";
        indent_ = 1;
        emit_block(n->body);
        // Trailing return guard
        if      (rt == "void")       line("return;");
        else if (rt == "long long")  line("return 0LL;");
        else if (rt == "double")     line("return 0.0;");
        else if (rt == "int")        line("return 0;");
        else                         line("return NULL;");
        indent_ = 0;
        out_ << "}\n";

        locals_        = std::move(saved_locals);
        current_ret_   = saved_ret;
        current_class_ = saved_cls;
        class_of_var_  = std::move(saved_cov);
        tmp_id_        = saved_tmp;
    }

    void emit_class(HirClassDef* cls) {
        for (auto& m : cls->methods) {
            if (m->kind == HirKind::FuncDef)
                emit_func(static_cast<HirFuncDef*>(m.get()), cls->name, true);
        }
    }

    void emit_lambda_def(const std::string& name, HirFuncDef* fn) {
        emit_func_named(name, fn->params, fn->return_type, fn->body);
        lambdas_.insert(name);
    }

    void emit_func_named(const std::string& name,
                         const std::vector<HirParam>& params,
                         const std::string& ret_type,
                         const HirBlock& body) {
        auto saved_locals = locals_;
        auto saved_ret    = current_ret_;
        int  saved_tmp    = tmp_id_;

        std::string rt = c_ret_type(ret_type);
        current_ret_ = rt;

        out_ << "\n" << rt << " " << name << "(";
        if (params.empty()) { out_ << "void"; }
        for (int i = 0; i < (int)params.size(); ++i) {
            if (i) out_ << ", ";
            std::string ct = c_type(params[i].type);
            out_ << ct << " " << params[i].name;
            locals_[params[i].name] = ct;
        }
        out_ << ") {\n";
        indent_ = 1;
        emit_block(body);
        if      (rt == "void")       line("return;");
        else if (rt == "long long")  line("return 0LL;");
        else if (rt == "double")     line("return 0.0;");
        else if (rt == "int")        line("return 0;");
        else                         line("return NULL;");
        indent_ = 0;
        out_ << "}\n";

        locals_      = std::move(saved_locals);
        current_ret_ = saved_ret;
        tmp_id_      = saved_tmp;
    }

    // Recursively collect HirFuncDef nodes nested inside function bodies.
    void collect_nested_funcs(const HirBlock& body, std::vector<HirFuncDef*>& out) {
        for (auto& n : body) {
            if (n->kind == HirKind::FuncDef) {
                out.push_back(static_cast<HirFuncDef*>(n.get()));
            } else if (n->kind == HirKind::If) {
                auto* i = static_cast<HirIf*>(n.get());
                collect_nested_funcs(i->then_block, out);
                collect_nested_funcs(i->else_block, out);
            } else if (n->kind == HirKind::While) {
                collect_nested_funcs(static_cast<HirWhile*>(n.get())->body, out);
            }
        }
    }

    void emit_lambda_local(HirFuncDef* n) {
        // Already emitted as a top-level function in the pre-pass; register as callable.
        lambdas_.insert(n->name);
    }
};

}  // namespace

void emit_c(std::ostream& out, const HirBlock& program, const std::string& filename) {
    CCodeGen gen(out);
    gen.emit_module(program, filename);
}

}  // namespace luz
