/*
 * luz_rt_class.c — Runtime class registry implementation.
 *
 * All class metadata is registered at startup by the compiled program's
 * prologue (generated by the Luz LLVM backend).  Method dispatch walks
 * the inheritance chain and calls the matching function pointer.
 */

#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

#include "luz_runtime.h"
#include "luz_rt_class.h"

/* ── Internal registry ──────────────────────────────────────────────────── */

#define LUZ_MAX_CLASSES  256
#define LUZ_MAX_ATTRS     64
#define LUZ_MAX_METHODS  (LUZ_MAX_CLASSES * 32)

typedef struct {
    uint32_t     class_id;
    uint32_t     parent_id;           /* 0 = no parent */
    char        *name;
    size_t       attr_count;
    char        *attr_names[LUZ_MAX_ATTRS];
    luz_vtable_t vtable;
    int          vtable_ready;
} luz_class_entry_t;

typedef struct {
    uint32_t  class_id;
    char     *name;
    void     *fn;
    int32_t   nparams;                /* including self */
} luz_method_reg_t;

static luz_class_entry_t g_classes[LUZ_MAX_CLASSES];
static int               g_class_count = 0;

static luz_method_reg_t  g_methods[LUZ_MAX_METHODS];
static int               g_method_count = 0;

/* ── Internal helpers ───────────────────────────────────────────────────── */

static luz_class_entry_t *_find_class(uint32_t id) {
    for (int i = 0; i < g_class_count; i++)
        if (g_classes[i].class_id == id) return &g_classes[i];
    return NULL;
}

static luz_vtable_t *_get_vtable(luz_class_entry_t *e) {
    if (e->vtable_ready) return &e->vtable;
    e->vtable.class_name = e->name;
    e->vtable.class_id   = e->class_id;
    e->vtable.attr_count = e->attr_count;
    e->vtable.attr_names = (const char **)e->attr_names;
    e->vtable_ready = 1;
    return &e->vtable;
}

static luz_method_reg_t *_find_method(uint32_t class_id, const char *name) {
    /* Walk the inheritance chain: check class, then its parent, etc. */
    uint32_t cur = class_id;
    while (cur != 0) {
        for (int i = 0; i < g_method_count; i++)
            if (g_methods[i].class_id == cur &&
                strcmp(g_methods[i].name, name) == 0)
                return &g_methods[i];
        luz_class_entry_t *e = _find_class(cur);
        cur = e ? e->parent_id : 0;
    }
    return NULL;
}

/* ── Registration API ───────────────────────────────────────────────────── */

void luz_rt_register_class(uint32_t class_id, const char *name,
                            size_t attr_count) {
    if (g_class_count >= LUZ_MAX_CLASSES) {
        fprintf(stderr, "luz: too many classes (limit %d)\n", LUZ_MAX_CLASSES);
        abort();
    }
    luz_class_entry_t *e = &g_classes[g_class_count++];
    memset(e, 0, sizeof(*e));
    e->class_id   = class_id;
    e->parent_id  = 0;
    e->name       = strdup(name);
    e->attr_count = attr_count;
}

void luz_rt_set_parent(uint32_t class_id, uint32_t parent_id) {
    luz_class_entry_t *e = _find_class(class_id);
    if (e) e->parent_id = parent_id;
}

void luz_rt_register_attr(uint32_t class_id, int32_t slot_index,
                           const char *name) {
    luz_class_entry_t *e = _find_class(class_id);
    if (!e || slot_index < 0 || slot_index >= LUZ_MAX_ATTRS) return;
    if (e->attr_names[slot_index]) free(e->attr_names[slot_index]);
    e->attr_names[slot_index] = strdup(name);
    /* Reset vtable so it is rebuilt with the new name next time. */
    e->vtable_ready = 0;
}

void luz_rt_register_method(uint32_t class_id, const char *name,
                              void *fn, int32_t nparams) {
    if (g_method_count >= LUZ_MAX_METHODS) {
        fprintf(stderr, "luz: too many methods (limit %d)\n", LUZ_MAX_METHODS);
        abort();
    }
    luz_method_reg_t *m = &g_methods[g_method_count++];
    m->class_id = class_id;
    m->name     = strdup(name);
    m->fn       = fn;
    m->nparams  = nparams;
}

/* ── Object creation ────────────────────────────────────────────────────── */

luz_value_t luz_rt_new_obj(uint32_t class_id) {
    luz_class_entry_t *e = _find_class(class_id);
    if (!e) {
        fprintf(stderr, "luz: ClassNotFoundError: unknown class_id %u\n",
                class_id);
        abort();
    }
    luz_vtable_t *vt = _get_vtable(e);
    luz_object_t *o  = luz_obj_new(vt);
    return LUZ_OBJ_VAL(o);
}

/* ── Method dispatch ────────────────────────────────────────────────────── */

luz_value_t luz_rt_obj_call(luz_value_t obj, const char *name,
                             luz_value_t *args, int32_t nargs) {
    if (obj.type != LUZ_OBJECT) {
        fprintf(stderr,
                "luz: TypeError: method call '%s' on non-object (type: %s)\n",
                name, luz_typeof(obj));
        abort();
    }
    uint32_t class_id = obj.obj->vtable ? obj.obj->vtable->class_id : 0;
    luz_method_reg_t *m = _find_method(class_id, name);
    if (!m) {
        fprintf(stderr, "luz: AttributeError: '%s' has no method '%s'\n",
                obj.obj->vtable ? obj.obj->vtable->class_name : "object",
                name);
        abort();
    }

    /* Dispatch based on nparams (includes self). */
    /* Methods are registered as pointer-only callbacks to avoid struct-by-value
       ABI mismatches between LLVM-generated code and GCC-compiled dispatch:
         void cb(luz_value_t *out, const luz_value_t *self, const luz_value_t *arg0, ...)
       Pointer args are ABI-neutral on all platforms. */
    typedef void (*cb1)(luz_value_t*, const luz_value_t*);
    typedef void (*cb2)(luz_value_t*, const luz_value_t*, const luz_value_t*);
    typedef void (*cb3)(luz_value_t*, const luz_value_t*, const luz_value_t*, const luz_value_t*);
    typedef void (*cb4)(luz_value_t*, const luz_value_t*, const luz_value_t*, const luz_value_t*, const luz_value_t*);
    typedef void (*cb5)(luz_value_t*, const luz_value_t*, const luz_value_t*, const luz_value_t*, const luz_value_t*, const luz_value_t*);
    typedef void (*cb6)(luz_value_t*, const luz_value_t*, const luz_value_t*, const luz_value_t*, const luz_value_t*, const luz_value_t*, const luz_value_t*);

    static const luz_value_t _null_val = { .type = LUZ_NULL };
#define _A(i) ((nargs) > (i) ? &(args)[(i)] : &_null_val)

    uintptr_t fn_addr = (uintptr_t)m->fn;
    luz_value_t result = _null_val;
    switch (m->nparams) {
        case 1: ((cb1)fn_addr)(&result, &obj); break;
        case 2: ((cb2)fn_addr)(&result, &obj, _A(0)); break;
        case 3: ((cb3)fn_addr)(&result, &obj, _A(0), _A(1)); break;
        case 4: ((cb4)fn_addr)(&result, &obj, _A(0), _A(1), _A(2)); break;
        case 5: ((cb5)fn_addr)(&result, &obj, _A(0), _A(1), _A(2), _A(3)); break;
        case 6: ((cb6)fn_addr)(&result, &obj, _A(0), _A(1), _A(2), _A(3), _A(4)); break;
        default:
            fprintf(stderr,
                    "luz: MethodDispatchError: unsupported param count %d "
                    "for method '%s' (max 6)\n", m->nparams, name);
            abort();
    }
#undef _A
    return result;
}

/* ── isinstance ─────────────────────────────────────────────────────────── */

luz_value_t luz_rt_isinstance(luz_value_t obj, uint32_t class_id) {
    if (obj.type != LUZ_OBJECT || !obj.obj->vtable)
        return LUZ_BOOL_VAL(0);
    uint32_t cur = obj.obj->vtable->class_id;
    while (cur != 0) {
        if (cur == class_id) return LUZ_BOOL_VAL(1);
        luz_class_entry_t *e = _find_class(cur);
        cur = e ? e->parent_id : 0;
    }
    return LUZ_BOOL_VAL(0);
}
